### ISSUE TITLE
ActiveJob & Lambda integration refers "bin/build-rails"

### ISSUE THREAD

**Issue by mtrolle** [customink/lamby-site#27]
In https://lamby.custominktech.com/docs/activejob_and_lambda in paragraph 4 you suggest creating a `Makefile` to setup a lambda function for ActiveJob execution.

Here you write:
> Now duplicate the bin/build-rails file and rename it to bin/build-jobs with the following contents. Effectively doing our source copy from the prior Lambda build.

but using the cookie cutter project I don't find any `bin/build-rails` script. So I'm unsure what is expected here.

**Comment by metaskills** [comment]
Thanks. That section did not get updated for containers yet. I'll have all the new documentation for the Lambdakiq gem written here. https://github.com/customink/lambdakiq

I'll post pack when done, should be later today.

**Comment by metaskills** [comment]
OK, Lambdakiq v1.0.1 is released and I updated this page (https://lamby.custominktech.com/docs/activejob_and_lambda) to point to here. https://github.com/customink/lambdakiq
