### ISSUE TITLE
Best practive - env variables in `template.yaml` file

### ISSUE THREAD

**Issue by fabiensebban** [customink/lamby-site#64]
The documentation recommends to use a mapping to get env variable for different environments...
https://github.com/rails-lambda/lamby-site/blob/dc4c3d2a040f34ff5133f131b585ec5106cf59a1/docs/environment.mdx?plain=1#L24-L38

... or use `x-crypteia-ssm:[...]` to get access to env variables from SSM. 

https://github.com/rails-lambda/lamby-site/blob/dc4c3d2a040f34ff5133f131b585ec5106cf59a1/docs/environment.mdx?plain=1#L50-L57

Wouldn't be easier to use the RailsEnv variable to get access to the correct SSM variable instead of using the mapping?
Here is an example:
 ```title="template.yaml" 
 Globals: 
   Environment: 
     Variables: 
       SECRET: x-crypteia-ssm:/myapp/${RailsEnv}/SECRET
 ```

This will get the env variable attached to a specific environment.

With this method, env variables won't be organized by services but it will decrease the file length.

**Comment by metaskills** [comment]
First, wanted to share that I was trying to strike a balance here in the the Lamby docs would be slim and link to full documentation within a separate project. Whatever we come up with, I'd like to try to maintain that.

WRT the RailsEnv... that is a 100% valid use case. It really depends on the AWS Account setup for a person or team. At Custom Ink we tried that SSM path convention and it ended up making things harder. What was easier for us is having a deterministic path that had different data as we had different AWS Account for staging and production. This of course is not likely the need for individuals or small teams. So I do think the guides can speak to that.

Would you be opening to making a PR that put just a tad bit more info into this section using the RailsEnv as an example and anything else mentioned here? https://github.com/rails-lambda/crypteia#usage

**Comment by fabiensebban** [comment]
Thanks you for the response!
Happy to see you validate my path convention. I loved the way env variables were used in the previous version of Lamby (with dotenv) and I wanted to re-use the same pattern.
The only thing missing is some script that creates SSM variables if they don't exist. It would save us a lot of time creating each SSM variable one by one.
I made a rake task to solve this problem : https://gist.github.com/fabiensebban/a2d4b1fa86586609043f9b09d0df71d5
Do you think we can integrate this rake tasks in Lamby?

I'll make the PR right now.
