### ISSUE TITLE
aws-embedded-metrics repo is no longer present 

### ISSUE THREAD

**Issue by jeremiahlukus** [customink/lamby-site#71]
in  https://lamby.cloud/docs/observability#cloudwatch-embedded-metrics  it mentions [rails-lambda/aws-embedded-metrics](https://github.com/rails-lambda/aws-embedded-metrics) however this repo 404's

Link to docs in repo:

https://github.com/rails-lambda/lamby-site/blob/2753b9b447984e713fd4a0a329265191c0bf6e73/docs/observability.mdx#cloudwatch-embedded-metrics

**Comment by jeremiahlukus** [comment]
It was moved to 
https://github.com/customink/aws-embedded-metrics-customink. (?)

Which is now read only

**Comment by metaskills** [comment]
Thanks, I forked that repo to here. Gem is still published in same place and I verified docs are good no.
